import Link from 'next/link';
import Navbar from '@/components/global/Navbar';
import Footer from '@/components/global/Footer';

const sections = [['What we collect', 'We collect account details, API key metadata, request logs, and support messages needed to operate TempCheck.'], ['How we use it', 'We use this information to authenticate requests, measure reliability, prevent abuse, provide support, and improve domain intelligence.'], ['Retention and access', 'Records are retained only as long as needed for operations, troubleshooting, fraud prevention, and contractual obligations. Access is limited to authorized team members.'], ['Your choices', 'You can request account information, correction, export, or deletion by contacting support. Some records may need to remain for security, billing, or legal compliance.']];

export default function PrivacyPage() {
  return <div className="app-layout" style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', background: 'var(--bg-main)' }}><Navbar /><main style={{ flex: '1 0 auto', padding: '48px 24px 72px' }}><article style={{ maxWidth: '820px', margin: '0 auto', padding: '28px', background: 'var(--bg-card)', border: '1px solid var(--border-default)', borderRadius: '3px' }}><div className="eyebrow" style={{ marginBottom: '12px' }}><span className="dot" />Legal &amp; compliance</div><h1 style={{ margin: '0 0 8px', color: 'var(--text-primary)', fontSize: 'clamp(28px, 4vw, 38px)' }}>Privacy Policy</h1><p style={{ margin: '0 0 28px', color: 'var(--text-muted)', fontSize: '12px' }}>Effective September 10, 2026 · TempCheck Inc.</p><p style={{ margin: '0 0 28px', color: 'var(--text-secondary)', fontSize: '14px', lineHeight: 1.7 }}>This policy explains how TempCheck handles information when you use our disposable-email detection API, dashboard, documentation, and support channels.</p><div style={{ display: 'grid', gap: '22px' }}>{sections.map(([title, body]) => <section key={title}><h2 style={{ margin: '0 0 6px', color: 'var(--text-primary)', fontSize: '17px' }}>{title}</h2><p style={{ margin: 0, color: 'var(--text-secondary)', fontSize: '13px', lineHeight: 1.7 }}>{body}</p></section>)}</div><div style={{ marginTop: '28px', paddingTop: '18px', borderTop: '1px solid var(--border-subtle)', color: 'var(--text-secondary)', fontSize: '13px' }}>Questions about privacy? <Link href="/contact" style={{ color: 'var(--primary)' }}>Contact support</Link>.</div></article></main><Footer /></div>;
}
